# Model Training 

- Train with tennis eras and test with 2024 matches
    
    - 1968-2023 (Open era)
    - 1990-2023 (Modern era)
    - 2024 (Tests Only)

- Use classic ML algorithms, such as:

    - Naive Bayes
    - SVM
    - Logistic Regression
    - KNN
    - Decision Tree
    - XGBoost

In [680]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import KFold, cross_val_score
from joblib import dump

## Load Data

In [3]:
target = pd.read_csv('../data/processed/5.1_data_target.csv', sep=';', encoding='utf-8')
target.head(3)

   SCORE
0      0
1      1
2      1

In [4]:
feature = pd.read_csv('../data/processed/5.1_data_feature.csv', sep=';', encoding='utf-8')
feature['SCORE'] = target['SCORE']
feature.head(3)

,TOURNEY_DATE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,PERC_0_WIN_LAST_10,...,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,SCORE
0,1967-12-28,-5.5,-5.5,2000.0,2000.000,0.000,2000.0,2000.000,0.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,1967-12-28,-0.4,-0.4,2000.0,1997.682,2.318,2000.0,1997.682,2.318,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,-0.0,-0.0,1
2,1967-12-28,-7.4,-7.4,2000.0,1996.842,3.158,2000.0,1996.842,3.158,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,-0.0,-0.0,1

In [5]:
feature_robust = pd.read_csv('../data/processed/5.2_data_feature_robust_esc.csv', sep=';', encoding='utf-8')
feature_robust['SCORE'] = target['SCORE']
feature_robust.head(3)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,TOURNEY_DATE,SCORE
0,-0.763889,-0.763889,-1.746527,-1.746527,0.000000,-0.823385,-0.823385,0.000000,-1.666667,-2.08,...,-1.666667,-2.285714,-2.526316,-2.611111,0.0,0.0,0.0,0.0,1967-12-28,0
1,-0.055556,-0.055556,-1.746527,-1.770650,0.022165,-0.823385,-0.845761,0.025099,-1.666667,-2.08,...,-1.666667,-2.285714,-2.526316,-2.611111,-0.0,-0.0,-0.0,-0.0,1967-12-28,1
2,-1.027778,-1.027778,-1.746527,-1.779391,0.030197,-0.823385,-0.853869,0.034195,-1.666667,-2.08,...,-1.666667,-2.285714,-2.526316,-2.611111,-0.0,-0.0,-0.0,-0.0,1967-12-28,1

In [6]:
feature_std = pd.read_csv('../data/processed/5.2_data_feature_std_esc.csv', sep=';', encoding='utf-8')
feature_std['SCORE'] = target['SCORE']
feature_std.head(3)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,TOURNEY_DATE,SCORE
0,-0.996229,-0.996229,-2.037945,-2.037945,4.567240e-19,-1.342667,-1.342667,-6.103064e-19,-2.433507,-2.884624,...,-2.026146,-2.345243,-2.472635,-2.532638,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19,1967-12-28,0
1,-0.072453,-0.072453,-2.037945,-2.068250,2.710429e-02,-1.342667,-1.378824,3.200140e-02,-2.433507,-2.884624,...,-2.026146,-2.345243,-2.472635,-2.532638,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19,1967-12-28,1
2,-1.340381,-1.340381,-2.037945,-2.079232,3.692637e-02,-1.342667,-1.391927,4.359810e-02,-2.433507,-2.884624,...,-2.026146,-2.345243,-2.472635,-2.532638,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19,1967-12-28,1

In [7]:
feature_pca = pd.read_csv('../data/processed/5.3_data_feature_robust_pca.csv', sep=';', encoding='utf-8')
feature_pca['SCORE'] = target['SCORE']
feature_pca.head(3)

,0,1,2,3,4,5,6,7,TOURNEY_DATE,SCORE
0,-6.612605,-0.184132,-1.541717,-1.046687,0.173026,0.696828,0.078319,0.379388,1967-12-28,0
1,-6.622805,0.011761,-1.545655,-0.074790,0.043871,0.676680,0.012100,0.376081,1967-12-28,1
2,-6.626502,-0.213474,-1.547082,-1.406453,0.275424,0.669379,0.114099,0.374882,1967-12-28,1

In [8]:
feature_lda = pd.read_csv('../data/processed/5.3_data_feature_robust_lda.csv', sep=';', encoding='utf-8')
feature_lda['SCORE'] = target['SCORE']
feature_lda.head(3)

          0 TOURNEY_DATE  SCORE
0 -0.285638   1967-12-28      0
1 -0.050722   1967-12-28      1
2 -0.425114   1967-12-28      1

## Train and Test Data

#### 1968-2023 (Train - Open era)

In [737]:
# open_data = feature_robust[feature_robust['TOURNEY_DATE'] < '2024-01-01']
# open_data = feature_std[feature_std['TOURNEY_DATE'] < '2024-01-01']
# open_data = feature_pca[feature_pca['TOURNEY_DATE'] < '2024-01-01']
# open_data = feature_lda[feature_lda['TOURNEY_DATE'] < '2024-01-01']
open_data = feature[feature['TOURNEY_DATE'] < '2024-01-01']
open_data.tail(3)

,TOURNEY_DATE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,PERC_0_WIN_LAST_10,...,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,SCORE
369519,2023-11-27,0.1,0.1,2087.350,2149.737,-62.387,2026.911,2086.482,-59.571,0.6,...,0.50,0.3,0.32,0.33,0.33,-0.3,-0.20,-0.17,-0.17,1
369520,2023-11-27,2.1,2.1,2065.886,2148.584,-82.698,2005.464,2085.486,-80.022,0.6,...,0.51,0.4,0.36,0.36,0.36,-0.2,-0.16,-0.15,-0.15,1
369521,2023-11-27,-1.1,-1.1,2078.038,2069.924,8.114,2016.725,2023.944,-7.219,0.4,...,0.38,0.6,0.58,0.58,0.58,0.2,0.20,0.20,0.20,1

In [738]:
y_open = open_data['SCORE']
X_open = open_data.drop(['SCORE', 'TOURNEY_DATE'], axis=1)

#### 1990-2023 (Train - Modern era)

In [739]:
# modern_data = feature_robust[(feature_robust['TOURNEY_DATE'] >= '1990-01-01') & ((feature_robust['TOURNEY_DATE'] < '2024-01-01'))]
# modern_data = feature_std[(feature_std['TOURNEY_DATE'] >= '1990-01-01') & ((feature_std['TOURNEY_DATE'] < '2024-01-01'))]
# modern_data = feature_pca[(feature_pca['TOURNEY_DATE'] >= '1990-01-01') & ((feature_pca['TOURNEY_DATE'] < '2024-01-01'))]
# modern_data = feature_lda[(feature_lda['TOURNEY_DATE'] >= '1990-01-01') & ((feature_lda['TOURNEY_DATE'] < '2024-01-01'))]
modern_data = feature[(feature['TOURNEY_DATE'] >= '1990-01-01') & ((feature['TOURNEY_DATE'] < '2024-01-01'))]
modern_data.head(3)

,TOURNEY_DATE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,PERC_0_WIN_LAST_10,...,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,SCORE
158388,1990-01-01,-0.1,-0.1,2213.228,2132.480,80.748,2107.767,2009.327,98.440,0.4,...,0.71,0.4,0.40,0.42,0.45,0.0,0.12,0.28,0.26,0
158389,1990-01-01,2.3,2.3,2132.453,2161.779,-29.326,2015.468,2013.169,2.299,0.6,...,0.63,0.6,0.52,0.52,0.52,-0.0,-0.12,-0.11,-0.11,1
158390,1990-01-01,-0.9,-0.9,2125.701,2180.741,-55.040,2031.092,2067.998,-36.906,0.6,...,0.44,0.4,0.32,0.36,0.36,-0.2,-0.12,-0.04,-0.08,1

In [740]:
y_modern = modern_data['SCORE']
X_modern = modern_data.drop(['SCORE', 'TOURNEY_DATE'], axis=1)

#### 2024 (Tests Only)

In [741]:
# matches_2024 = feature_robust[(feature_robust['TOURNEY_DATE'] >= '2024-01-01')]
# matches_2024 = feature_std[feature_std['TOURNEY_DATE'] >= '2024-01-01']
# matches_2024 = feature_pca[feature_pca['TOURNEY_DATE'] >= '2024-01-01']
# matches_2024 = feature_lda[feature_lda['TOURNEY_DATE'] >= '2024-01-01']
matches_2024 = feature[feature['TOURNEY_DATE'] >= '2024-01-01']
matches_2024.head(3)

,TOURNEY_DATE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,PERC_0_WIN_LAST_10,...,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF,SCORE
369522,2024-01-01,7.0,7.0,2178.369,2066.184,112.185,2131.664,2041.972,89.692,0.3,...,0.27,0.5,0.60,0.64,0.62,0.2,0.33,0.37,0.35,1
369523,2024-01-01,2.4,2.4,2192.935,2190.444,2.491,2139.723,2142.684,-2.961,0.8,...,0.64,0.6,0.48,0.48,0.53,-0.2,-0.28,-0.16,-0.11,1
369524,2024-01-01,2.9,2.9,2120.322,2186.739,-66.417,2040.784,2147.551,-106.767,0.5,...,0.50,0.5,0.36,0.44,0.44,-0.0,-0.12,-0.06,-0.06,1

In [742]:
y_2024 = matches_2024['SCORE']
X_2024 = matches_2024.drop(['SCORE', 'TOURNEY_DATE'], axis=1)

## Model Training

### Naive Bayes

#### Open

In [687]:
gnb_open = GaussianNB()

In [688]:
gnb_open.fit(X_open, y_open)

GaussianNB()

In [689]:
predict_gnb_open = gnb_open.predict(X_2024)
predict_gnb_open

array([0, 1, 1, ..., 0, 1, 1], shape=(5944,))

In [691]:
accuracy_gnb_open = accuracy_score(y_2024, predict_gnb_open)
print(f'Accuracy: {(accuracy_gnb_open * 100):.2f}%')

Accuracy: 65.75%

In [692]:
confusion_matrix(y_2024, predict_gnb_open)

array([[1954, 1018],
       [1018, 1954]])

In [693]:
print(classification_report(y_2024, predict_gnb_open))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66      2972
           1       0.66      0.66      0.66      2972

    accuracy                           0.66      5944
   macro avg       0.66      0.66      0.66      5944
weighted avg       0.66      0.66      0.66      5944

In [694]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [695]:
gnb_open2 = GaussianNB()
result = cross_val_score(gnb_open2, X_open, y_open, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

Accuracy: 69.44 %

#### Modern

In [696]:
gnb_modern = GaussianNB()

In [697]:
gnb_modern.fit(X_modern, y_modern)

GaussianNB()

In [698]:
predict_gnb_modern = gnb_modern.predict(X_2024)
predict_gnb_modern

array([0, 1, 1, ..., 0, 1, 1], shape=(5944,))

In [699]:
accuracy_gnb_modern = accuracy_score(y_2024, predict_gnb_modern)
print(f'Accuracy: {(accuracy_gnb_modern * 100):.2f}%')

Accuracy: 65.75%

In [700]:
confusion_matrix(y_2024, predict_gnb_modern)

array([[1954, 1018],
       [1018, 1954]])

In [701]:
print(classification_report(y_2024, predict_gnb_modern))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66      2972
           1       0.66      0.66      0.66      2972

    accuracy                           0.66      5944
   macro avg       0.66      0.66      0.66      5944
weighted avg       0.66      0.66      0.66      5944

In [702]:
kfold2 = KFold(n_splits=5, shuffle=True, random_state=5)

In [703]:
gnb_modern2 = GaussianNB()
result2 = cross_val_score(gnb_modern2, X_modern, y_modern, cv=kfold2)
print(f'Accuracy: {(result2.mean() * 100):.2f}%')

Accuracy: 67.83%

#### Naive Bayes Result

- Open data
    - Accuracy: 65.75%
    - Confusion Matrix 
        - array([[1954, 1018],
        [1018, 1954]])
    - Cross Validation 69.44%
- Modern data
    - Accuracy: 65.75%
    - Confusion Matrix 
        - array([[1954, 1018],
           [1018, 1954]])
    - Cross Validation 67.83%

- **Best**: Open Data with LDA + Robust Scaler

#### Save Best Naive Bayes Model

In [704]:
dump(gnb_open, '../models/gnb_model.joblib')

['../models/gnb_model.joblib']

### SVM

#### Open

In [711]:
svc_open = SVC(kernel='rbf', C=1, max_iter=2000) #NOSONAR

In [712]:
svc_open.fit(X_open, y_open)

c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

SVC(C=1, max_iter=2000)

In [713]:
predict_svc_open = svc_open.predict(X_2024)
predict_svc_open.tolist().count(0)

2984

In [714]:
accuracy_svc_open = accuracy_score(y_2024, predict_svc_open)
print(f'Accuracy: {(accuracy_svc_open * 100):.2f}%')

Accuracy: 94.52%

In [715]:
confusion_matrix(y_2024, predict_svc_open)

array([[2815,  157],
       [ 169, 2803]])

In [716]:
print(classification_report(y_2024, predict_svc_open))

              precision    recall  f1-score   support

           0       0.94      0.95      0.95      2972
           1       0.95      0.94      0.95      2972

    accuracy                           0.95      5944
   macro avg       0.95      0.95      0.95      5944
weighted avg       0.95      0.95      0.95      5944

In [717]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [224]:
svc_open2 = SVC(kernel='rbf', C=1, max_iter=2000) #NOSONAR
result = cross_val_score(svc_open2, X_open, y_open, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

Accuracy: 92.98 %

#### Modern

In [ ]:
svc_modern = SVC(kernel='rbf', C=1, max_iter=2000) #NOSONAR

In [226]:
svc_modern.fit(X_modern, y_modern)

c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

SVC(C=1, max_iter=2000)

In [227]:
predict_svc_modern = svc_modern.predict(X_2024)
predict_svc_modern

array([1, 1, 1, ..., 1, 1, 1], shape=(5944,))

In [228]:
accuracy_svc_modern = accuracy_score(y_2024, predict_svc_modern)
print(f'Accuracy: {(accuracy_svc_modern * 100):.2f}%')

Accuracy: 93.74%

In [242]:
confusion_matrix(y_2024, predict_svc_modern)

array([[2682,  290],
       [  82, 2890]])

In [ ]:
print(classification_report(y_2024, predict_svc_modern))

              precision    recall  f1-score   support

           0       0.97      0.90      0.94      2972
           1       0.91      0.97      0.94      2972

    accuracy                           0.94      5944
   macro avg       0.94      0.94      0.94      5944
weighted avg       0.94      0.94      0.94      5944

In [232]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [233]:
svc_modern2 = SVC(kernel='rbf', C=1, max_iter=2000) #NOSONAR
result = cross_val_score(svc_modern2, X_modern, y_modern, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\phrug\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_base.py:305: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

Accuracy: 94.91 %

#### SVM Result

- Open data
    - Accuracy: 94.52%
    - Confusion Matrix 
        - array([[2815,  157],
       [169, 2803]])
    - Cross Validation 92.98%
- Modern data
    - Accuracy: 93.74%
    - Confusion Matrix 
        - array([[2682,  290],
            [82, 2890]])
    - Cross Validation 94.91%

- **Best**: Open Data with Robust Scaler

#### Save SVM Model

In [718]:
dump(svc_open, '../models/svc_model.joblib')

['../models/svc_model.joblib']

### Logistic Regression

#### Open

In [213]:
lr_open = LogisticRegression(C=10, penalty='l2', solver='lbfgs', max_iter=500, random_state=1)

In [214]:
lr_open.fit(X_open, y_open)

LogisticRegression(C=10, max_iter=500, random_state=1)

In [215]:
predict_lr_open = lr_open.predict(X_2024)
predict_lr_open

array([0, 1, 1, ..., 0, 1, 1], shape=(5944,))

In [216]:
accuracy_lr_open = accuracy_score(y_2024, predict_lr_open)
print(f'Accuracy: {(accuracy_lr_open * 100):.2f}%')

Accuracy: 65.71%

In [217]:
confusion_matrix(y_2024, predict_lr_open)

array([[1953, 1019],
       [1019, 1953]])

In [218]:
print(classification_report(y_2024, predict_lr_open))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66      2972
           1       0.66      0.66      0.66      2972

    accuracy                           0.66      5944
   macro avg       0.66      0.66      0.66      5944
weighted avg       0.66      0.66      0.66      5944

In [219]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [220]:
lr_open2 = LogisticRegression(C=10, penalty='l2', solver='lbfgs', max_iter=500, random_state=1)
result = cross_val_score(lr_open2, X_open, y_open, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

Accuracy: 69.47 %

#### Modern

In [221]:
lr_modern = LogisticRegression(C=10, penalty='l2', solver='lbfgs', max_iter=500, random_state=1)

In [222]:
lr_modern.fit(X_modern, y_modern)

LogisticRegression(C=10, max_iter=500, random_state=1)

In [223]:
predict_lr_modern = lr_modern.predict(X_2024)
predict_lr_modern

array([0, 1, 1, ..., 0, 1, 1], shape=(5944,))

In [224]:
accuracy_lr_modern = accuracy_score(y_2024, predict_lr_modern)
print(f'Accuracy: {(accuracy_lr_modern * 100):.2f}%')

Accuracy: 66.12%

In [225]:
confusion_matrix(y_2024, predict_lr_modern)

array([[1965, 1007],
       [1007, 1965]])

In [226]:
print(classification_report(y_2024, predict_lr_modern))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66      2972
           1       0.66      0.66      0.66      2972

    accuracy                           0.66      5944
   macro avg       0.66      0.66      0.66      5944
weighted avg       0.66      0.66      0.66      5944

In [227]:
kfold2 = KFold(n_splits=5, shuffle=True, random_state=5)

In [228]:
lr_modern2 = LogisticRegression(C=10, penalty='l2', solver='lbfgs', max_iter=500, random_state=1)
result2 = cross_val_score(lr_modern2, X_modern, y_modern, cv=kfold2)
print(f'Accuracy: {(result2.mean() * 100):.2f}%')

Accuracy: 67.83%

#### Logistic Regression Result

- Open data (LDA)
    - Accuracy: 65.75%
    - Confusion Matrix 
        - array([[1954, 1018],
        [1018, 1954]])
    - Cross Validation 69.44%
- Modern data (PCA + Robust)
    - Accuracy: 66.12%
    - Confusion Matrix 
        - array([[1965, 1007],
       [1007, 1965]])
    - Cross Validation 67.83%

- **Best**: Modern Data with PCA + Robust Scaler

#### Save Logistic Regression Best Model

In [719]:
dump(lr_modern, '../models/logistic_regression_model.joblib')

['../models/logistic_regression_model.joblib']

### KNN

#### Open

In [726]:
knn_open = KNeighborsClassifier(n_neighbors=10, metric='minkowski', p=1, n_jobs=-1)

In [727]:
knn_open.fit(X_open, y_open)

KNeighborsClassifier(n_jobs=-1, n_neighbors=10, p=1)

In [728]:
predict_knn_open = knn_open.predict(X_2024)
predict_knn_open

array([1, 1, 1, ..., 1, 1, 1], shape=(5944,))

In [729]:
accuracy_knn_open = accuracy_score(y_2024, predict_knn_open)
print(f'Accuracy: {(accuracy_knn_open * 100):.2f}%')

Accuracy: 98.86%

In [730]:
confusion_matrix(y_2024, predict_knn_open)

array([[2947,   25],
       [  43, 2929]])

In [731]:
print(classification_report(y_2024, predict_knn_open))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2972
           1       0.99      0.99      0.99      2972

    accuracy                           0.99      5944
   macro avg       0.99      0.99      0.99      5944
weighted avg       0.99      0.99      0.99      5944

In [732]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [733]:
knn_open2 = KNeighborsClassifier(n_neighbors=10, metric='minkowski', p=1, n_jobs=-1)
result = cross_val_score(knn_open2, X_open, y_open, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

Accuracy: 98.54 %

#### Modern

In [353]:
knn_modern = KNeighborsClassifier(n_neighbors=10, metric='minkowski', p=1, n_jobs=-1)

In [354]:
knn_modern.fit(X_modern, y_modern)

KNeighborsClassifier(n_jobs=-1, n_neighbors=10, p=1)

In [355]:
predict_knn_modern = knn_modern.predict(X_2024)
predict_knn_modern

array([0, 1, 1, ..., 0, 1, 0], shape=(5944,))

In [356]:
accuracy_knn_modern = accuracy_score(y_2024, predict_knn_modern)
print(f'Accuracy: {(accuracy_knn_modern * 100):.2f}%')

Accuracy: 62.69%

In [357]:
confusion_matrix(y_2024, predict_knn_modern)

array([[2032,  940],
       [1278, 1694]])

In [358]:
print(classification_report(y_2024, predict_knn_modern))

              precision    recall  f1-score   support

           0       0.61      0.68      0.65      2972
           1       0.64      0.57      0.60      2972

    accuracy                           0.63      5944
   macro avg       0.63      0.63      0.63      5944
weighted avg       0.63      0.63      0.63      5944

In [359]:
kfold2 = KFold(n_splits=5, shuffle=True, random_state=5)

In [360]:
knn_modern2 = KNeighborsClassifier(n_neighbors=10, metric='minkowski', p=1, n_jobs=-1)
result2 = cross_val_score(knn_modern2, X_modern, y_modern, cv=kfold2)
print(f'Accuracy: {(result2.mean() * 100):.2f}%')

Accuracy: 64.95%

#### KNN Result

- Open data (Robust)
    - Accuracy: 98.86%
    - Confusion Matrix 
        - array([[2947,   25],
       [  43, 2929]])
    - Cross Validation 98.54%
- Modern data (PCA + Robust)
    - Accuracy: 95.73%
    - Confusion Matrix 
        - array([[2881,   91],
       [ 163, 2809]])
    - Cross Validation 95.92%

- **Best**: Open Data with Robust Scaler

#### Save KNN Best Model

In [734]:
dump(knn_open, '../models/knn_model.joblib')

['../models/knn_model.joblib']

### Decision Tree

#### Open

In [537]:
dt_open = DecisionTreeClassifier(max_depth=20, random_state=1, criterion='gini', ccp_alpha=0)

In [538]:
dt_open.fit(X_open, y_open)

DecisionTreeClassifier(ccp_alpha=0, max_depth=20, random_state=1)

In [539]:
predict_dt_open = dt_open.predict(X_2024)
predict_dt_open

array([1, 1, 1, ..., 1, 1, 1], shape=(5944,))

In [540]:
accuracy_dt_open = accuracy_score(y_2024, predict_dt_open)
print(f'Accuracy: {(accuracy_dt_open * 100):.2f}%')

Accuracy: 98.92%

In [541]:
confusion_matrix(y_2024, predict_dt_open)

array([[2938,   34],
       [  30, 2942]])

In [542]:
print(classification_report(y_2024, predict_dt_open))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2972
           1       0.99      0.99      0.99      2972

    accuracy                           0.99      5944
   macro avg       0.99      0.99      0.99      5944
weighted avg       0.99      0.99      0.99      5944

In [543]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [544]:
dt_open2 = DecisionTreeClassifier(max_depth=20, random_state=1, criterion='gini', ccp_alpha=0)
result = cross_val_score(dt_open2, X_open, y_open, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

Accuracy: 98.90 %

#### Modern

In [545]:
dt_modern = DecisionTreeClassifier(max_depth=20, random_state=1, criterion='gini', ccp_alpha=0)

In [546]:
dt_modern.fit(X_modern, y_modern)

DecisionTreeClassifier(ccp_alpha=0, max_depth=20, random_state=1)

In [547]:
predict_dt_modern = dt_modern.predict(X_2024)
predict_dt_modern

array([1, 1, 1, ..., 1, 1, 1], shape=(5944,))

In [548]:
accuracy_dt_modern = accuracy_score(y_2024, predict_dt_modern)
print(f'Accuracy: {(accuracy_dt_modern * 100):.2f}%')

Accuracy: 98.81%

In [549]:
confusion_matrix(y_2024, predict_dt_modern)

array([[2938,   34],
       [  37, 2935]])

In [550]:
print(classification_report(y_2024, predict_dt_modern))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2972
           1       0.99      0.99      0.99      2972

    accuracy                           0.99      5944
   macro avg       0.99      0.99      0.99      5944
weighted avg       0.99      0.99      0.99      5944

In [551]:
kfold2 = KFold(n_splits=5, shuffle=True, random_state=5)

In [552]:
dt_modern2 = DecisionTreeClassifier(max_depth=20, random_state=1, criterion='gini', ccp_alpha=0)
result2 = cross_val_score(dt_modern2, X_modern, y_modern, cv=kfold2)
print(f'Accuracy: {(result2.mean() * 100):.2f}%')

Accuracy: 98.88%

#### Decision Tree Result

- Open data
    - Accuracy: 98.92%
    - Confusion Matrix 
        - array([[2938,   34],
       [  30, 2942]])
    - Cross Validation 98.90%
- Modern data
    - Accuracy: 98.81%
    - Confusion Matrix 
        - array([[2938,   34],
       [  37, 2935]])
    - Cross Validation 98.88%

- **Best**: Raw Open Data

#### Save Decision Tree Best Model

In [735]:
dump(dt_open, '../models/decision_tree_model.joblib')

['../models/decision_tree_model.joblib']

### XGBoost

#### Open

In [664]:
xgb_open = XGBClassifier(max_depth=20, n_estimators=100, learning_rate=0.05, objective='binary:logistic', random_state=3)

In [665]:
xgb_open.fit(X_open, y_open)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=20,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [666]:
predict_xgb_open = xgb_open.predict(X_2024)
predict_xgb_open

array([1, 1, 1, ..., 1, 1, 1], shape=(5944,))

In [667]:
accuracy_xgb_open = accuracy_score(y_2024, predict_xgb_open)
print(f'Accuracy: {(accuracy_xgb_open * 100):.2f}%')

Accuracy: 99.50%

In [657]:
confusion_matrix(y_2024, predict_xgb_open)

array([[2959,   13],
       [  17, 2955]])

In [668]:
print(classification_report(y_2024, predict_xgb_open))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      2972
           1       1.00      0.99      0.99      2972

    accuracy                           0.99      5944
   macro avg       0.99      0.99      0.99      5944
weighted avg       0.99      0.99      0.99      5944

In [669]:
kfold = KFold(n_splits=5, shuffle=True, random_state=5)

In [679]:
xgb_open2 = XGBClassifier(max_depth=20, n_estimators=100, learning_rate=0.05, objective='binary:logistic', random_state=3)
result = cross_val_score(xgb_open2, X_open, y_open, cv=kfold)
print(f'Accuracy: {(result.mean() * 100):.2f} %')

Accuracy: 99.48 %

#### Modern

In [670]:
xgb_modern = XGBClassifier(max_depth=20, n_estimators=100, learning_rate=0.05, objective='binary:logistic', random_state=3)

In [671]:
xgb_modern.fit(X_modern, y_modern)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=20,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [672]:
predict_xgb_modern = xgb_modern.predict(X_2024)
predict_xgb_modern

array([1, 1, 1, ..., 1, 1, 1], shape=(5944,))

In [673]:
accuracy_xgb_modern = accuracy_score(y_2024, predict_xgb_modern)
print(f'Accuracy: {(accuracy_xgb_modern * 100):.2f}%')

Accuracy: 99.36%

In [674]:
confusion_matrix(y_2024, predict_xgb_modern)

array([[2952,   20],
       [  18, 2954]])

In [675]:
print(classification_report(y_2024, predict_xgb_modern))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2972
           1       0.99      0.99      0.99      2972

    accuracy                           0.99      5944
   macro avg       0.99      0.99      0.99      5944
weighted avg       0.99      0.99      0.99      5944

In [676]:
kfold2 = KFold(n_splits=5, shuffle=True, random_state=5)

In [677]:
xgb_modern2 = XGBClassifier()
result2 = cross_val_score(xgb_modern2, X_modern, y_modern, cv=kfold2)
print(f'Accuracy: {(result2.mean() * 100):.2f}%')

Accuracy: 99.66%

#### XGBoost Result

- Open data
    - Accuracy: 99.50%
    - Confusion Matrix 
        - array([[2959,   13],
       [  17, 2955]])
    - Cross Validation 99.48%

- Modern data
    - Accuracy: 99.36%
    - Confusion Matrix 
        - array([[2952,   20],
       [  18, 2954]])  
    - Cross Validation 99.66%

- **Best**: Raw Open Data

#### Save XGBoost Best Model

In [736]:
dump(xgb_open, '../models/xgboost_model.joblib')

['../models/xgboost_model.joblib']

# Model Training Result

Best Model
- XGBoost using raw open data
    - Accuracy: 99.50%
    - Confusion Matrix 
        - array([[2959,   13],
       [  17, 2955]])
    - Cross Validation 99.48%

TODO:
- Create Pipeline
- Test with recent games